[package]
name = "marmotte-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
bytes = "1.10.1"
crc32fast = "1.5.0"
filesize = "0.2.0"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
